# Generated by Django 4.2.2 on 2023-06-25 07:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=3)),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', verbose_name=65)),
                ('fname', models.CharField(default='', verbose_name=65)),
                ('date_of_birth', models.DateField(verbose_name=datetime.datetime.now)),
                ('address', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='SchoolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1)),
                ('address', models.CharField(default='', max_length=200)),
                ('info', models.JSONField(default='')),
            ],
            options={
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=67)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='ParentsModel',
            fields=[
                ('personmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kundalik.personmodel')),
                ('user_name', models.CharField(default='', max_length=65)),
                ('password', models.CharField(default='', max_length=40)),
            ],
            options={
                'db_table': 'parent',
            },
            bases=('kundalik.personmodel',),
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('personmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kundalik.personmodel')),
                ('toifa', models.CharField(default='', max_length=50)),
                ('salary', models.PositiveIntegerField(default=1)),
                ('school', models.ManyToManyField(to='kundalik.schoolmodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kundalik.subjectmodel')),
            ],
            options={
                'db_table': 'teacher',
            },
            bases=('kundalik.personmodel',),
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('personmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kundalik.personmodel')),
                ('user_name', models.CharField(default='', max_length=65)),
                ('password', models.CharField(default='', max_length=40)),
                ('avtivate', models.BooleanField(default=False)),
                ('phone', models.CharField(default='', max_length=13)),
                ('clasS', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kundalik.classmodel')),
                ('parents', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kundalik.parentsmodel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kundalik.schoolmodel')),
            ],
            options={
                'db_table': 'student',
            },
            bases=('kundalik.personmodel',),
        ),
        migrations.CreateModel(
            name='GradeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('mark', models.PositiveSmallIntegerField(default=1)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kundalik.subjectmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kundalik.studentmodel')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kundalik.teachermodel')),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kundalik.subjectmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kundalik.studentmodel')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kundalik.teachermodel')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
