# Generated by Django 4.2.2 on 2023-06-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kundalik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmodel',
            name='info',
            field=models.CharField(default=''),
        ),
    ]
