# Generated by Django 4.2.2 on 2023-06-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kundalik', '0002_alter_schoolmodel_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmodel',
            name='info',
            field=models.JSONField(),
        ),
    ]
