# Generated by Django 4.2.2 on 2023-06-25 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kundalik', '0004_alter_classmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='fname',
            field=models.CharField(default='', max_length=65),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='name',
            field=models.CharField(default='', max_length=65),
        ),
    ]
