# Generated by Django 4.2.2 on 2023-06-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kundalik', '0005_alter_personmodel_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='toifa',
            field=models.CharField(choices=[('OM', "Oliy Ma'lumot"), ('OR', "O'rta Ma'lumot"), ('OP', "O'qituvchi Pedagok")], default='', max_length=2),
        ),
    ]
